# Site settings
title: The Pulpit
header-img: img/skyline.jpg
email: author@theplpt.com
copyright_name: The Pulpit
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
#twitter_username: 
#facebook_username:  
email_username:  author@theplpt.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

#category stuff
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed, jekyll-paginate-multiple]

paginate_multiple:
  - paginate: 1
    paginate_path: '/blog/page:num/'
    sub_dir: '/blog'
  - paginate: 1
    paginate_path: '/blog/category/albums/page:num/'
    sub_dir: '/blog/category/albums'
