# Site settings
title: The Pulpit
header-img: img/skyline.jpg
email: your-email@yourdomain.com
copyright_name: The Pulpit
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: SBootstrap
facebook_username:  StartBootstrap
email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

plugins: [jekyll-paginate, jekyll-feed]
